Repository three-ping/SyncDay_Back, pull requests merged in 2024-11, with the labels that each got.

#16 feat: 참여 상태 컬럼에 역할 저장
  build.gradle
  src/main/java/com/threeping/syncday/common/exception/ErrorCode.java
  src/main/java/com/threeping/syncday/proj/command/application/controller/AppProjController.java
  src/main/java/com/threeping/syncday/proj/command/application/service/AppProjService.java
  src/main/java/com/threeping/syncday/proj/command/application/service/AppProjServiceImpl.java
  src/main/java/com/threeping/syncday/proj/command/infrastructure/service/InfraProjService.java
  src/main/java/com/threeping/syncday/proj/command/infrastructure/service/InfraProjServiceImpl.java
  src/main/java/com/threeping/syncday/proj/query/controller/ProjController.java
  src/main/java/com/threeping/syncday/proj/query/repository/ProjMapper.java
  src/main/java/com/threeping/syncday/proj/query/service/ProjService.java
  src/main/java/com/threeping/syncday/proj/query/service/ProjServiceImpl.java
  src/main/java/com/threeping/syncday/projmember/command/aggregate/entity/BookmarkStatus.java
  src/main/java/com/threeping/syncday/projmember/command/aggregate/entity/ParticipationStatus.java
  src/main/java/com/threeping/syncday/projmember/command/aggregate/entity/ProjMember.java
  src/main/java/com/threeping/syncday/projmember/command/aggregate/entity/ProjMemberPK.java
  src/main/java/com/threeping/syncday/projmember/command/application/controller/AppProjMemberController.java
  src/main/java/com/threeping/syncday/projmember/command/application/service/AppProjMemberService.java
  src/main/java/com/threeping/syncday/projmember/command/application/service/AppProjMemberServiceImpl.java
  src/main/java/com/threeping/syncday/projmember/command/domain/repository/ProjMemberRepository.java
  src/main/java/com/threeping/syncday/projmember/query/aggregate/ProjMember.java
  src/main/java/com/threeping/syncday/projmember/query/aggregate/ProjMemberDTO.java
  src/main/java/com/threeping/syncday/projmember/query/config/MybatisConfig.java
  src/main/java/com/threeping/syncday/projmember/query/controller/ProjMemberController.java
  src/main/java/com/threeping/syncday/projmember/query/repository/ProjMemberMapper.java
  src/main/java/com/threeping/syncday/projmember/query/service/ProjMemberService.java
  src/main/java/com/threeping/syncday/projmember/query/service/ProjMemberServiceImpl.java
  src/main/java/com/threeping/syncday/user/command/application/controller/UserCommandController.java
  src/main/java/com/threeping/syncday/user/command/application/service/UserCommandService.java
  src/main/java/com/threeping/syncday/user/command/application/service/UserCommandServiceImpl.java
  src/main/java/com/threeping/syncday/user/command/domain/aggregate/UserEntity.java
  src/main/java/com/threeping/syncday/user/command/domain/repository/UserRepository.java
  src/main/java/com/threeping/syncday/user/command/domain/vo/LoginRequestVO.java
  src/main/java/com/threeping/syncday/user/command/domain/vo/RegistRequestVO.java
  src/main/java/com/threeping/syncday/user/command/domain/vo/ResponseNormalLoginVO.java
  src/main/java/com/threeping/syncday/user/config/AppConfig.java
  src/main/java/com/threeping/syncday/user/config/MybatisConfig.java
  src/main/java/com/threeping/syncday/user/config/RedisConfig.java
  src/main/java/com/threeping/syncday/user/query/controller/UserController.java
  src/main/java/com/threeping/syncday/user/query/controller/UserQueryController.java
  src/main/java/com/threeping/syncday/user/query/dto/UserDTO.java
  src/main/java/com/threeping/syncday/user/query/repository/UserMapper.java
  src/main/java/com/threeping/syncday/user/query/service/UserQueryService.java
  src/main/java/com/threeping/syncday/user/query/service/UserQueryServiceImpl.java
  src/main/java/com/threeping/syncday/user/security/AuthenticationFilter.java
  src/main/java/com/threeping/syncday/user/security/HMACKeyGenerator.java
  src/main/java/com/threeping/syncday/user/security/WebSecurity.java
  src/main/resources/application.yml
  src/main/resources/com/threeping/syncday/projmember/query/repository/ProjMemberMapper.xml
  src/main/resources/com/threeping/syncday/user/query/repository/UserMapper.xml
  src/test/java/com/threeping/syncday/proj/command/application/service/AppProjServiceTests.java
  src/test/java/com/threeping/syncday/proj/query/service/ProjServiceTests.java
  src/test/java/com/threeping/syncday/projmember/query/service/ProjMemberServiceTests.java
Labels: enhancement

#18 chore: controller method이름 수정
  src/main/java/com/threeping/syncday/proj/command/application/controller/AppProjController.java
Labels: enhancement

#29 feature: 팀 기본 구조 세팅(CRUD)
  src/main/java/com/threeping/syncday/meetingroom/command/aggregate/dto/MeetingroomDTO.java
  src/main/java/com/threeping/syncday/meetingroom/command/aggregate/entity/Meetingroom.java
  src/main/java/com/threeping/syncday/meetingroom/command/application/controller/AppMeetingroomController.java
  src/main/java/com/threeping/syncday/team/command/aggregate/dto/TeamDTO.java
  src/main/java/com/threeping/syncday/team/command/aggregate/entity/Team.java
  src/main/java/com/threeping/syncday/team/command/application/controller/AppTeamController.java
  src/main/java/com/threeping/syncday/team/command/application/service/AppTeamService.java
  src/main/java/com/threeping/syncday/team/command/application/service/AppTeamServiceImpl.java
  src/main/java/com/threeping/syncday/team/command/domain/TeamRepository.java
  src/main/java/com/threeping/syncday/team/query/aggregate/Team.java
  src/main/java/com/threeping/syncday/team/query/aggregate/TeamDTO.java
  src/main/java/com/threeping/syncday/team/query/config/MybatisConfig.java
  src/main/java/com/threeping/syncday/team/query/controller/TeamController.java
  src/main/java/com/threeping/syncday/team/query/repository/TeamMapper.java
  src/main/java/com/threeping/syncday/team/query/service/TeamService.java
  src/main/java/com/threeping/syncday/team/query/service/TeamServiceImpl.java
  src/main/resources/com/threeping/syncday/team/query/repository/TeamMapper.xml
  src/test/java/com/threeping/syncday/team/command/application/service/AppTeamServiceTests.java
  src/test/java/com/threeping/syncday/team/query/controller/TeamControllerTests.java
  src/test/java/com/threeping/syncday/team/query/service/TeamServiceTests.java
Labels: feat✨, BackEnd🔙

#26 Feature/user 백엔드 기본 구현 완료
  build.gradle
  src/main/java/com/threeping/syncday/common/ResponseDTO.java
  src/main/java/com/threeping/syncday/common/exception/ErrorCode.java
  src/main/java/com/threeping/syncday/common/exception/GlobalExceptionHandler.java
  src/main/java/com/threeping/syncday/config/SwaggerConfiguration.java
  src/main/java/com/threeping/syncday/user/command/application/controller/UserCommandController.java
  src/main/java/com/threeping/syncday/user/command/application/dto/UserDTO.java
  src/main/java/com/threeping/syncday/user/command/application/service/UserCommandService.java
  src/main/java/com/threeping/syncday/user/command/application/service/UserCommandServiceImpl.java
  src/main/java/com/threeping/syncday/user/command/domain/aggregate/UserEntity.java
  src/main/java/com/threeping/syncday/user/command/domain/vo/LoginRequestVO.java
  src/main/java/com/threeping/syncday/user/command/domain/vo/PwdChangeRequestVO.java
  src/main/java/com/threeping/syncday/user/command/domain/vo/RegistRequestVO.java
  src/main/java/com/threeping/syncday/user/command/domain/vo/ResponseNormalLoginVO.java
  src/main/java/com/threeping/syncday/user/config/RedisConfig.java
  src/main/java/com/threeping/syncday/user/query/controller/AuthDocsController.java
  src/main/java/com/threeping/syncday/user/query/controller/UserQueryController.java
  src/main/java/com/threeping/syncday/user/query/dto/UserDTO.java
  src/main/java/com/threeping/syncday/user/query/repository/UserMapper.java
  src/main/java/com/threeping/syncday/user/query/service/UserQueryService.java
  src/main/java/com/threeping/syncday/user/query/service/UserQueryServiceImpl.java
  src/main/java/com/threeping/syncday/user/security/AuthenticationFilter.java
  src/main/java/com/threeping/syncday/user/security/CustomLogoutHandler.java
  src/main/java/com/threeping/syncday/user/security/JwtFilter.java
  src/main/java/com/threeping/syncday/user/security/JwtUtil.java
  src/main/java/com/threeping/syncday/user/security/WebSecurity.java
  src/main/resources/application.yml
  src/main/resources/com/threeping/syncday/user/query/repository/UserMapper.xml
  src/test/java/com/threeping/syncday/user/command/application/service/UserCommandServiceTests.java
  src/test/java/com/threeping/syncday/user/query/service/UserQueryServiceTests.java
Labels: feat✨

#34 feat: 일정 생성, 수정, 삭제 기능 개발
  src/main/java/com/threeping/syncday/common/enumtype/MeetingStatus.java
  src/main/java/com/threeping/syncday/common/enumtype/ParticipationStatus.java
  src/main/java/com/threeping/syncday/common/enumtype/PublicStatus.java
  src/main/java/com/threeping/syncday/schedule/command/Infrastructure/InfraScheduleService.java
  src/main/java/com/threeping/syncday/schedule/command/Infrastructure/InfraScheduleServiceImpl.java
  src/main/java/com/threeping/syncday/schedule/command/aggregate/dto/ScheduleDTO.java
  src/main/java/com/threeping/syncday/schedule/command/aggregate/entity/Schedule.java
  src/main/java/com/threeping/syncday/schedule/command/application/controller/AppScheduleController.java
  src/main/java/com/threeping/syncday/schedule/command/application/service/AppScheduleService.java
  src/main/java/com/threeping/syncday/schedule/command/application/service/AppScheduleServiceImpl.java
  src/main/java/com/threeping/syncday/schedule/command/domain/repository/ScheduleRepository.java
  src/main/java/com/threeping/syncday/schedule/query/aggregate/Schedule.java
  src/main/java/com/threeping/syncday/schedule/query/aggregate/ScheduleDTO.java
  src/main/java/com/threeping/syncday/schedule/query/config/MybatisConfig.java
  src/main/java/com/threeping/syncday/schedule/query/controller/ScheduleController.java
  src/main/java/com/threeping/syncday/schedule/query/repository/ScheduleMapper.java
  src/main/java/com/threeping/syncday/schedule/query/service/ScheduleService.java
  src/main/java/com/threeping/syncday/schedule/query/service/ScheduleServiceImpl.java
  src/main/java/com/threeping/syncday/scheduleparticipant/command/aggregate/entity/ScheduleParticipant.java
  src/main/java/com/threeping/syncday/scheduleparticipant/command/aggregate/entity/ScheduleParticipantPK.java
  src/main/java/com/threeping/syncday/scheduleparticipant/command/application/service/AppScheduleParticipantService.java
  src/main/java/com/threeping/syncday/scheduleparticipant/command/application/service/AppScheduleParticipantServiceImpl.java
  src/main/java/com/threeping/syncday/scheduleparticipant/command/domain/repository/ScheduleParticipantRepository.java
  src/main/resources/com/threeping/syncday/schedule/query/repository/ScheduleMapper.xml
  src/test/java/com/threeping/syncday/schedule/command/application/service/AppScheduleServiceTests.java
Labels: feat✨, BackEnd🔙

#35 refactor: mapper 수정
  src/main/resources/application.yml
  src/main/resources/com/threeping/syncday/team/query/repository/TeamMapper.xml
Labels: BackEnd🔙, refactor✂️

#36 Feature/chat
  build.gradle
  src/main/java/com/threeping/syncday/chat/config/WebConfig.java
  src/main/java/com/threeping/syncday/chat/config/WebSocketConfig.java
  src/main/java/com/threeping/syncday/chat/dto/ChatMessageDTO.java
  src/main/java/com/threeping/syncday/chat/dto/ChatRoomDTO.java
  src/main/java/com/threeping/syncday/chat/dto/FileUploadDTO.java
  src/main/java/com/threeping/syncday/chat/entity/ChatMessage.java
  src/main/java/com/threeping/syncday/chat/entity/ChatRoom.java
  src/main/java/com/threeping/syncday/chat/entity/ChatType.java
  src/main/java/com/threeping/syncday/chat/repository/ChatMessageRepository.java
  src/main/java/com/threeping/syncday/chat/repository/ChatRoomRepository.java
  src/main/java/com/threeping/syncday/chat/service/ChatService.java
Labels: feat✨, BackEnd🔙

#39 feature: 회의실 생성&수정&삭제
  src/main/java/com/threeping/syncday/meetingroom/command/application/controller/AppMeetingroomController.java
  src/main/java/com/threeping/syncday/meetingroom/command/application/service/AppMeetingroomService.java
  src/main/java/com/threeping/syncday/meetingroom/command/application/service/AppMeetingroomServiceImpl.java
  src/main/java/com/threeping/syncday/meetingroom/command/domain/repository/MeetingroomRepository.java
Labels: feat✨, BackEnd🔙

#40 feat(schedule) : 일정 조회 기능 개발
  src/main/java/com/threeping/syncday/schedule/query/controller/ScheduleController.java
  src/main/java/com/threeping/syncday/schedule/query/repository/ScheduleMapper.java
  src/main/java/com/threeping/syncday/schedule/query/service/ScheduleService.java
  src/main/java/com/threeping/syncday/schedule/query/service/ScheduleServiceImpl.java
  src/main/resources/com/threeping/syncday/schedule/query/repository/ScheduleMapper.xml
  src/test/java/com/threeping/syncday/schedule/query/service/ScheduleServiceTests.java
Labels: feat✨, BackEnd🔙

#41 Fix: rt를 httponly 쿠키에 담도록 수정
  build.gradle
  src/main/java/com/threeping/syncday/common/ResponseDTO.java
  src/main/java/com/threeping/syncday/common/exception/ErrorCode.java
  src/main/java/com/threeping/syncday/common/exception/GlobalExceptionHandler.java
  src/main/java/com/threeping/syncday/user/command/application/controller/UserCommandController.java
  src/main/java/com/threeping/syncday/user/command/domain/vo/LoginRequestVO.java
  src/main/java/com/threeping/syncday/user/query/controller/AuthDocsController.java
  src/main/java/com/threeping/syncday/user/query/service/UserQueryServiceImpl.java
  src/main/java/com/threeping/syncday/user/security/AuthenticationFilter.java
  src/main/java/com/threeping/syncday/user/security/CustomLogoutHandler.java
  src/main/java/com/threeping/syncday/user/security/JwtFilter.java
  src/main/java/com/threeping/syncday/user/security/JwtUtil.java
Labels: feat✨, BackEnd🔙, fix🛠️

#43 FIX: 로그아웃 시, cookie를 만료시켜 rt를 갖고 다니지 않게 수정
  build.gradle
  src/main/java/com/threeping/syncday/chat/config/WebConfig.java
  src/main/java/com/threeping/syncday/chat/config/WebSocketConfig.java
  src/main/java/com/threeping/syncday/chat/dto/ChatMessageDTO.java
  src/main/java/com/threeping/syncday/chat/dto/ChatRoomDTO.java
  src/main/java/com/threeping/syncday/chat/dto/FileUploadDTO.java
  src/main/java/com/threeping/syncday/chat/entity/ChatMessage.java
  src/main/java/com/threeping/syncday/chat/entity/ChatRoom.java
  src/main/java/com/threeping/syncday/chat/entity/ChatType.java
  src/main/java/com/threeping/syncday/chat/repository/ChatMessageRepository.java
  src/main/java/com/threeping/syncday/chat/repository/ChatRoomRepository.java
  src/main/java/com/threeping/syncday/chat/service/ChatService.java
  src/main/java/com/threeping/syncday/common/ResponseDTO.java
  src/main/java/com/threeping/syncday/config/WebConfig.java
  src/main/java/com/threeping/syncday/user/command/application/controller/UserCommandController.java
  src/main/java/com/threeping/syncday/user/command/application/service/UserCommandServiceImpl.java
  src/main/java/com/threeping/syncday/user/command/domain/vo/LoginRequestVO.java
  src/main/java/com/threeping/syncday/user/command/domain/vo/RegistRequestVO.java
  src/main/java/com/threeping/syncday/user/command/domain/vo/ResponseNormalLoginVO.java
  src/main/java/com/threeping/syncday/user/query/controller/UserQueryController.java
  src/main/java/com/threeping/syncday/user/query/service/UserQueryService.java
  src/main/java/com/threeping/syncday/user/query/service/UserQueryServiceImpl.java
  src/main/java/com/threeping/syncday/user/security/CustomLogoutHandler.java
  src/main/java/com/threeping/syncday/user/security/JwtFilter.java
  src/main/java/com/threeping/syncday/user/security/JwtUtil.java
  src/main/resources/application.yml
Labels: BackEnd🔙, fix🛠️

#44 feat(schedule-repeat): 반복일정 생성 기능 추가
  src/main/java/com/threeping/syncday/common/enumtype/MeetingStatus.java
  src/main/java/com/threeping/syncday/common/enumtype/ParticipationStatus.java
  src/main/java/com/threeping/syncday/common/enumtype/PublicStatus.java
  src/main/java/com/threeping/syncday/common/exception/ErrorCode.java
  src/main/java/com/threeping/syncday/common/mail/aggregate/MailType.java
  src/main/java/com/threeping/syncday/common/mail/service/MailService.java
  src/main/java/com/threeping/syncday/common/mail/service/MailServiceImpl.java
  src/main/java/com/threeping/syncday/config/AsyncConfig.java
  src/main/java/com/threeping/syncday/schedule/command/aggregate/dto/ScheduleDTO.java
  src/main/java/com/threeping/syncday/schedule/command/aggregate/entity/MeetingStatus.java
  src/main/java/com/threeping/syncday/schedule/command/aggregate/entity/PublicStatus.java
  src/main/java/com/threeping/syncday/schedule/command/aggregate/entity/Schedule.java
  src/main/java/com/threeping/syncday/schedule/query/aggregate/Schedule.java
  src/main/java/com/threeping/syncday/schedule/query/aggregate/ScheduleDTO.java
  src/main/java/com/threeping/syncday/scheduleparticipant/command/aggregate/entity/ParticipationStatus.java
  src/main/java/com/threeping/syncday/scheduleparticipant/command/aggregate/entity/ScheduleParticipant.java
  src/main/java/com/threeping/syncday/schedulerepeat/command/aggregate/dto/CreateRepeatedScheduleDTO.java
  src/main/java/com/threeping/syncday/schedulerepeat/command/aggregate/dto/CreateScheduleRepeatDTO.java
  src/main/java/com/threeping/syncday/schedulerepeat/command/aggregate/dto/RepeatDTO.java
  src/main/java/com/threeping/syncday/schedulerepeat/command/aggregate/dto/SendScheduleRepeatMailDTO.java
  src/main/java/com/threeping/syncday/schedulerepeat/command/aggregate/entity/MeetingStatus.java
  src/main/java/com/threeping/syncday/schedulerepeat/command/aggregate/entity/PersonalMonthlyType.java
  src/main/java/com/threeping/syncday/schedulerepeat/command/aggregate/entity/PersonalRecurrenceUnit.java
  src/main/java/com/threeping/syncday/schedulerepeat/command/aggregate/entity/PublicStatus.java
  src/main/java/com/threeping/syncday/schedulerepeat/command/aggregate/entity/RecurrenceType.java
  src/main/java/com/threeping/syncday/schedulerepeat/command/aggregate/entity/ScheduleRepeat.java
  src/main/java/com/threeping/syncday/schedulerepeat/command/aggregate/vo/ScheduleDurationVO.java
  src/main/java/com/threeping/syncday/schedulerepeat/command/application/controller/ScheduleRepeatCommandController.java
  src/main/java/com/threeping/syncday/schedulerepeat/command/application/service/ScheduleRepeatCommandService.java
  src/main/java/com/threeping/syncday/schedulerepeat/command/application/service/ScheduleRepeatCommandServiceImpl.java
  src/main/java/com/threeping/syncday/schedulerepeat/command/domain/repository/ScheduleRepeatRepository.java
  src/main/java/com/threeping/syncday/schedulerepeat/command/domain/service/ScheduleRepeatDomainService.java
  src/main/java/com/threeping/syncday/schedulerepeat/command/domain/service/ScheduleRepeatDomainServiceImpl.java
  src/main/java/com/threeping/syncday/schedulerepeat/command/infrastructure/service/InfraScheduleRepeatService.java
  src/main/java/com/threeping/syncday/schedulerepeat/command/infrastructure/service/InfraScheduleRepeatServiceImpl.java
  src/main/java/com/threeping/syncday/schedulerepeat/query/aggregate/ScheduleRepeat.java
  src/main/java/com/threeping/syncday/schedulerepeat/query/config/MybatisConfig.java
  src/main/java/com/threeping/syncday/schedulerepeat/query/controller/ScheduleRepeatQueryController.java
  src/main/java/com/threeping/syncday/schedulerepeat/query/repository/ScheduleRepeatMapper.java
  src/main/java/com/threeping/syncday/schedulerepeat/query/service/ScheduleRepeatQueryService.java
  src/main/java/com/threeping/syncday/schedulerepeat/query/service/ScheduleRepeatQueryServiceImpl.java
  src/main/java/com/threeping/syncday/schedulerepeatparticipant/command/aggregate/entity/ParticipationStatus.java
  src/main/java/com/threeping/syncday/schedulerepeatparticipant/command/aggregate/entity/ScheduleRepeatParticipant.java
  src/main/java/com/threeping/syncday/schedulerepeatparticipant/command/aggregate/entity/ScheduleRepeatParticipantPK.java
  src/main/java/com/threeping/syncday/schedulerepeatparticipant/command/application/controller/ScheduleRepeatParticipantCommandController.java
  src/main/java/com/threeping/syncday/schedulerepeatparticipant/command/application/service/ScheduleRepeatParticipantService.java
  src/main/java/com/threeping/syncday/schedulerepeatparticipant/command/application/service/ScheduleRepeatParticipantServiceImpl.java
  src/main/java/com/threeping/syncday/schedulerepeatparticipant/command/domain/repository/ScheduleRepeatParticipantRepository.java
  src/main/resources/com/threeping/syncday/schedulerepeat/query/repository/ScheduleRepeatMapper.xml
  src/main/resources/templates/SCHEDULE_REPEAT.html
  src/test/java/com/threeping/syncday/schedulerepeat/command/application/service/ScheduleRepeatCommandServiceImplTests.java
Labels: feat✨, BackEnd🔙

#55 feature: 회의실 예약 생성 수정 삭제
  build.gradle
  src/main/java/com/threeping/syncday/meetingroomreservation/command/aggregate/dto/MeetingroomReservationDTO.java
  src/main/java/com/threeping/syncday/meetingroomreservation/command/aggregate/entity/MeetingroomReservation.java
  src/main/java/com/threeping/syncday/meetingroomreservation/command/application/controller/AppMeetingroomReservationController.java
  src/main/java/com/threeping/syncday/meetingroomreservation/command/application/service/AppMeetingroomReservationService.java
  src/main/java/com/threeping/syncday/meetingroomreservation/command/application/service/AppMeetingroomReservationServiceImpl.java
  src/main/java/com/threeping/syncday/meetingroomreservation/command/domain/repository/MeetingroomReservationRepository.java
  src/main/java/com/threeping/syncday/meetingroomreservation/command/infrastructure/InfraMeetingroomReservationService.java
  src/main/java/com/threeping/syncday/meetingroomreservation/command/infrastructure/InfraMeetingroomReservationServiceImpl.java
  src/main/java/com/threeping/syncday/meetingroomreservation/query/aggregate/MeetingroomReservation.java
  src/main/java/com/threeping/syncday/meetingroomreservation/query/aggregate/MeetingroomReservationDTO.java
  src/main/java/com/threeping/syncday/meetingroomreservation/query/config/MybatisConfig.java
  src/main/java/com/threeping/syncday/meetingroomreservation/query/controller/MeetingroomReservationController.java
  src/main/java/com/threeping/syncday/meetingroomreservation/query/repository/MeetingroomReservationMapper.java
  src/main/java/com/threeping/syncday/meetingroomreservation/query/service/MeetingroomReservationService.java
  src/main/java/com/threeping/syncday/meetingroomreservation/query/service/MeetingroomReservationServiceImpl.java
  src/main/java/com/threeping/syncday/schedule/command/application/service/AppScheduleService.java
  src/main/java/com/threeping/syncday/schedule/command/application/service/AppScheduleServiceImpl.java
  src/main/resources/com/threeping/syncday/meetingroomreservation/query/repository/MeetingroomReservationMapper.xml
  src/test/java/com/threeping/syncday/meetingroomreservation/command/application/service/AppMeetingroomReservationServiceTests.java
  src/test/java/com/threeping/syncday/meetingroomreservation/query/service/MeetingroomReservationServiceTests.java
Labels: feat✨, BackEnd🔙

#53 [Proj] 프로젝트 ID로 멤버 리스트 조회, 프로젝트 생성, 수정
  src/main/java/com/threeping/syncday/SyncdayApplication.java
  src/main/java/com/threeping/syncday/proj/query/aggregate/dto/ProjAndMemberDTO.java
  src/main/java/com/threeping/syncday/proj/query/aggregate/dto/ProjDTO.java
  src/main/java/com/threeping/syncday/proj/query/controller/ProjController.java
  src/main/java/com/threeping/syncday/proj/query/repository/ProjMapper.java
  src/main/java/com/threeping/syncday/proj/query/service/ProjService.java
  src/main/java/com/threeping/syncday/proj/query/service/ProjServiceImpl.java
  src/main/java/com/threeping/syncday/projmember/command/aggregate/entity/ProjMember.java
  src/main/java/com/threeping/syncday/projmember/command/aggregate/entity/ProjMemberPK.java
  src/main/java/com/threeping/syncday/projmember/command/domain/repository/ProjMemberRepository.java
  src/main/java/com/threeping/syncday/projmember/query/aggregate/ProjMember.java
  src/main/java/com/threeping/syncday/projmember/query/aggregate/ProjMemberDTO.java
  src/main/java/com/threeping/syncday/projmember/query/controller/ProjMemberController.java
  src/main/java/com/threeping/syncday/projmember/query/repository/ProjMemberMapper.java
  src/main/java/com/threeping/syncday/projmember/query/service/ProjMemberService.java
  src/main/java/com/threeping/syncday/projmember/query/service/ProjMemberServiceImpl.java
  src/main/resources/com/threeping/syncday/proj/query/repository/ProjMapper.xml
  src/main/resources/com/threeping/syncday/projmember/query/repository/ProjMemberMapper.xml
  src/test/java/com/threeping/syncday/proj/query/service/ProjServiceTests.java
  src/test/java/com/threeping/syncday/projmember/query/service/ProjMemberServiceTests.java
Labels: BackEnd🔙

#56 refractor: AppMeetingroomReservationServiceImpl 수정
  src/main/java/com/threeping/syncday/meetingroomreservation/command/application/service/AppMeetingroomReservationServiceImpl.java
Labels: BackEnd🔙, refactor✂️

#59 FIX: 로그인 시, nav바에 유저정보 잘 나오도록 수정
  src/main/java/com/threeping/syncday/user/command/domain/vo/ResponseNormalLoginVO.java
Labels: BackEnd🔙, fix🛠️

#62 feat: 카드보드 조회
  src/main/java/com/threeping/syncday/card/query/aggregate/Card.java
  src/main/java/com/threeping/syncday/card/query/aggregate/CardDTO.java
  src/main/java/com/threeping/syncday/card/query/config/MybatisConfig.java
  src/main/java/com/threeping/syncday/card/query/controller/CardController.java
  src/main/java/com/threeping/syncday/card/query/repository/CardMapper.java
  src/main/java/com/threeping/syncday/card/query/service/CardService.java
  src/main/java/com/threeping/syncday/card/query/service/CardServiceImpl.java
  src/main/java/com/threeping/syncday/cardboard/query/aggregate/CardBoard.java
  src/main/java/com/threeping/syncday/cardboard/query/aggregate/CardBoardDTO.java
  src/main/java/com/threeping/syncday/cardboard/query/config/MybatisConfig.java
  src/main/java/com/threeping/syncday/cardboard/query/controller/CardBoardController.java
  src/main/java/com/threeping/syncday/cardboard/query/repository/CardBoardMapper.java
  src/main/java/com/threeping/syncday/cardboard/query/service/CardBoardService.java
  src/main/java/com/threeping/syncday/cardboard/query/service/CardBoardServiceImpl.java
  src/main/java/com/threeping/syncday/proj/query/aggregate/dto/ProjAndWorkspaceDTO.java
  src/main/java/com/threeping/syncday/proj/query/controller/ProjController.java
  src/main/java/com/threeping/syncday/proj/query/repository/ProjMapper.java
  src/main/java/com/threeping/syncday/proj/query/service/ProjService.java
  src/main/java/com/threeping/syncday/proj/query/service/ProjServiceImpl.java
  src/main/java/com/threeping/syncday/workspace/query/aggregate/CardBoardVO.java
  src/main/java/com/threeping/syncday/workspace/query/aggregate/CardVO.java
  src/main/java/com/threeping/syncday/workspace/query/aggregate/WorkspaceInfoDTO.java
  src/main/java/com/threeping/syncday/workspace/query/controller/WorkspaceController.java
  src/main/java/com/threeping/syncday/workspace/query/respository/WorkspaceMapper.java
  src/main/java/com/threeping/syncday/workspace/query/service/WorkspaceService.java
  src/main/java/com/threeping/syncday/workspace/query/service/WorkspaceServiceImpl.java
  src/main/resources/com/threeping/syncday/card/query/repository/CardMapper.xml
  src/main/resources/com/threeping/syncday/cardboard/query/repository/CardBoardMapper.xml
  src/main/resources/com/threeping/syncday/proj/query/repository/ProjMapper.xml
  src/main/resources/com/threeping/syncday/workspace/query/respository/WorkspaceMapper.xml
  src/test/java/com/threeping/syncday/card/query/service/CardServiceTests.java
  src/test/java/com/threeping/syncday/cardboard/query/service/CardBoardServiceTests.java
  src/test/java/com/threeping/syncday/proj/query/service/ProjServiceTests.java
  src/test/java/com/threeping/syncday/workspace/query/service/WorkspaceServiceTests.java
Labels: BackEnd🔙

#70 Feature/user
  build.gradle
  src/main/java/com/threeping/syncday/chat/controller/ChatController.java
  src/main/java/com/threeping/syncday/chat/entity/ChatType.java
  src/main/java/com/threeping/syncday/chat/service/ChatService.java
  src/main/java/com/threeping/syncday/config/WebConfig.java
  src/main/java/com/threeping/syncday/user/command/domain/aggregate/CustomUser.java
  src/main/java/com/threeping/syncday/user/query/controller/UserQueryController.java
  src/main/java/com/threeping/syncday/user/query/service/UserQueryServiceImpl.java
  src/main/java/com/threeping/syncday/user/security/AuthenticationFilter.java
  src/main/java/com/threeping/syncday/user/security/JwtFilter.java
  src/main/java/com/threeping/syncday/user/security/JwtUtil.java
Labels: BackEnd🔙, fix🛠️

#71 feat(ScheduleRepeat): 일정반복 삭제 기능 추가
  src/main/java/com/threeping/syncday/schedulerepeat/command/aggregate/dto/ScheduleRepeatDTO.java
  src/main/java/com/threeping/syncday/schedulerepeat/command/aggregate/dto/UpdateScheduleRepeatDTO.java
  src/main/java/com/threeping/syncday/schedulerepeat/command/application/controller/ScheduleRepeatCommandController.java
  src/main/java/com/threeping/syncday/schedulerepeat/command/application/service/ScheduleRepeatCommandService.java
  src/main/java/com/threeping/syncday/schedulerepeat/command/application/service/ScheduleRepeatCommandServiceImpl.java
  src/main/java/com/threeping/syncday/schedulerepeatparticipant/command/application/controller/ScheduleRepeatParticipantCommandController.java
  src/main/resources/templates/SCHEDULE_REPEAT.html
  src/test/java/com/threeping/syncday/schedulerepeat/command/application/service/ScheduleRepeatCommandServiceImplTests.java
Labels: feat✨, BackEnd🔙

#72 refactor(schedule) : 일정 생성, 수정, 조회 수정
  build.gradle
  src/main/java/com/threeping/syncday/schedule/command/Infrastructure/InfraScheduleService.java
  src/main/java/com/threeping/syncday/schedule/command/Infrastructure/InfraScheduleServiceImpl.java
  src/main/java/com/threeping/syncday/schedule/command/aggregate/dto/ScheduleDTO.java
  src/main/java/com/threeping/syncday/schedule/command/application/service/AppScheduleServiceImpl.java
  src/main/java/com/threeping/syncday/schedule/query/aggregate/ScheduleDetailDTO.java
  src/main/java/com/threeping/syncday/scheduleparticipant/command/aggregate/dto/ResponseScheduleParticipantDTO.java
  src/main/java/com/threeping/syncday/scheduleparticipant/command/aggregate/dto/ScheduleParticipantNotificationDTO.java
  src/main/java/com/threeping/syncday/scheduleparticipant/command/aggregate/dto/ScheduleParticipantStatusDTO.java
  src/main/java/com/threeping/syncday/scheduleparticipant/command/aggregate/entity/ScheduleParticipant.java
  src/main/java/com/threeping/syncday/scheduleparticipant/command/application/controller/AppScheduleParticipantController.java
  src/main/java/com/threeping/syncday/scheduleparticipant/command/application/service/AppScheduleParticipantService.java
  src/main/java/com/threeping/syncday/scheduleparticipant/command/application/service/AppScheduleParticipantServiceImpl.java
  src/main/java/com/threeping/syncday/scheduleparticipant/command/domain/repository/ScheduleParticipantRepository.java
  src/main/java/com/threeping/syncday/scheduleparticipant/query/aggregate/ScheduleParticipantDTO.java
  src/main/java/com/threeping/syncday/scheduleparticipant/query/config/MybatisConfig.java
  src/main/java/com/threeping/syncday/scheduleparticipant/query/repository/ScheduleParticipantMapper.java
  src/main/java/com/threeping/syncday/scheduleparticipant/query/service/ScheduleParticipantService.java
  src/main/java/com/threeping/syncday/scheduleparticipant/query/service/ScheduleParticipantServiceImpl.java
  src/main/resources/com/threeping/syncday/schedule/query/repository/ScheduleMapper.xml
  src/main/resources/com/threeping/syncday/scheduleparticipant/query/repository/ScheduleParticipantMapper.xml
  src/test/java/com/threeping/syncday/scheduleparticipant/command/application/service/AppScheduleParticipantServiceTests.java
  src/test/java/com/threeping/syncday/scheduleparticipant/query/service/ScheduleParticipantServiceTests.java
Labels: BackEnd🔙, refactor✂️

#73 feature(notification) 일정 시작 전 알림 기능 추가
  src/main/java/com/threeping/syncday/SyncdayApplication.java
  src/main/java/com/threeping/syncday/notification/config/RedisNotificationListenerConfig.java
  src/main/java/com/threeping/syncday/notification/config/RedisNotificationPubSubConfig.java
  src/main/java/com/threeping/syncday/notification/config/RedisNotificationTopicConfig.java
  src/main/java/com/threeping/syncday/notification/controller/NotificationSseController.java
  src/main/java/com/threeping/syncday/notification/infrastructure/InfraNotificationService.java
  src/main/java/com/threeping/syncday/notification/infrastructure/InfraNotificationServiceImpl.java
  src/main/java/com/threeping/syncday/notification/redis/RedisNotificationStorage.java
  src/main/java/com/threeping/syncday/notification/redis/RedisNotificationSubscriber.java
  src/main/java/com/threeping/syncday/notification/service/NotificationScheduler.java
  src/main/java/com/threeping/syncday/notification/service/NotificationService.java
  src/main/java/com/threeping/syncday/notification/service/NotificationServiceImpl.java
  src/main/java/com/threeping/syncday/notification/service/TestUserSchedule.java
  src/main/java/com/threeping/syncday/schedule/query/repository/ScheduleMapper.java
  src/main/java/com/threeping/syncday/schedule/query/service/ScheduleService.java
  src/main/java/com/threeping/syncday/schedule/query/service/ScheduleServiceImpl.java
  src/main/java/com/threeping/syncday/user/security/JwtFilter.java
  src/main/java/com/threeping/syncday/user/security/WebSecurity.java
  src/main/resources/com/threeping/syncday/schedule/query/repository/ScheduleMapper.xml
Labels: feat✨, BackEnd🔙

#74 refactor(schedule) : 일정 도메인 수정 및 Swagger 작성
  src/main/java/com/threeping/syncday/schedule/command/aggregate/dto/ScheduleDTO.java
  src/main/java/com/threeping/syncday/schedule/command/application/controller/AppScheduleController.java
  src/main/java/com/threeping/syncday/schedule/command/application/service/AppScheduleServiceImpl.java
  src/main/java/com/threeping/syncday/schedule/query/aggregate/ScheduleDTO.java
  src/main/java/com/threeping/syncday/schedule/query/controller/ScheduleController.java
  src/main/java/com/threeping/syncday/scheduleparticipant/command/aggregate/dto/ScheduleParticipantNotificationDTO.java
  src/main/java/com/threeping/syncday/scheduleparticipant/command/aggregate/dto/ScheduleParticipantStatusDTO.java
  src/main/java/com/threeping/syncday/scheduleparticipant/command/application/controller/AppScheduleParticipantController.java
  src/main/resources/com/threeping/syncday/schedule/query/repository/ScheduleMapper.xml
  src/main/resources/com/threeping/syncday/scheduleparticipant/query/repository/ScheduleParticipantMapper.xml
Labels: BackEnd🔙, refactor✂️

#75 refactor(schedule) : 일정 조회 및 Swagger 수정
  src/main/java/com/threeping/syncday/config/SwaggerConfiguration.java
  src/main/resources/com/threeping/syncday/schedule/query/repository/ScheduleMapper.xml
Labels: BackEnd🔙, refactor✂️

#76 회의실 및 회의실 예약 추가
  build.gradle
  src/main/java/com/threeping/syncday/meetingroom/query/aggregate/MeetingroomDTO.java
  src/main/java/com/threeping/syncday/meetingroom/query/controller/MeetingroomController.java
  src/main/java/com/threeping/syncday/meetingroom/query/repository/MeetingroomMapper.java
  src/main/java/com/threeping/syncday/meetingroom/query/service/MeetingroomService.java
  src/main/java/com/threeping/syncday/meetingroom/query/service/MeetingroomServiceImpl.java
  src/main/java/com/threeping/syncday/meetingroomreservation/command/application/controller/AppMeetingroomReservationController.java
  src/main/java/com/threeping/syncday/meetingroomreservation/command/application/service/AppMeetingroomReservationServiceImpl.java
  src/main/java/com/threeping/syncday/meetingroomreservation/query/controller/MeetingroomReservationController.java
  src/main/java/com/threeping/syncday/meetingroomreservation/query/repository/MeetingroomReservationMapper.java
  src/main/java/com/threeping/syncday/meetingroomreservation/query/service/MeetingroomReservationService.java
  src/main/java/com/threeping/syncday/meetingroomreservation/query/service/MeetingroomReservationServiceImpl.java
  src/main/java/com/threeping/syncday/proj/command/aggregate/entity/Proj.java
  src/main/resources/com/threeping/syncday/meetingroom/query/repository/MeetingroomMapper.xml
  src/main/resources/com/threeping/syncday/meetingroomreservation/query/repository/MeetingroomReservationMapper.xml
  src/test/java/com/threeping/syncday/meetingroom/query/service/MeetingroomServiceTests.java
Labels: feat✨, BackEnd🔙

#77 Refactor: 회의실 Swagger 수정
  src/main/java/com/threeping/syncday/config/SwaggerConfiguration.java
  src/main/java/com/threeping/syncday/meetingroomreservation/command/aggregate/dto/MeetingroomReservationDTO.java
  src/main/java/com/threeping/syncday/meetingroomreservation/command/application/service/AppMeetingroomReservationServiceImpl.java
  src/main/java/com/threeping/syncday/schedule/command/application/service/AppScheduleServiceImpl.java
Labels: BackEnd🔙, refactor✂️

#78 유저 PK로 유저 조회 기능 추가 및 프로젝트 검색 기능 추가
  build.gradle
  src/main/java/com/threeping/syncday/config/AppConfiguration.java
  src/main/java/com/threeping/syncday/proj/command/aggregate/dto/ProjectEventDTO.java
  src/main/java/com/threeping/syncday/proj/command/aggregate/entity/Proj.java
  src/main/java/com/threeping/syncday/proj/infrastructure/elasticsearch/ElasticsearchInitializer.java
  src/main/java/com/threeping/syncday/proj/infrastructure/elasticsearch/document/ProjectSearchDocument.java
  src/main/java/com/threeping/syncday/proj/infrastructure/elasticsearch/repository/ProjSearchRepository.java
  src/main/java/com/threeping/syncday/proj/query/aggregate/dto/ProjectQueryDTO.java
  src/main/java/com/threeping/syncday/proj/query/aggregate/dto/ProjectSearchResponse.java
  src/main/java/com/threeping/syncday/proj/query/config/ProjectEntityListener.java
  src/main/java/com/threeping/syncday/proj/query/config/elasticsearch/ProjectSearchEventHandler.java
  src/main/java/com/threeping/syncday/proj/query/controller/ProjController.java
  src/main/java/com/threeping/syncday/proj/query/repository/ProjMapper.java
  src/main/java/com/threeping/syncday/proj/query/service/ProjectSearchService.java
  src/main/java/com/threeping/syncday/proj/query/service/ProjectSearchServiceImpl.java
  src/main/java/com/threeping/syncday/user/command/application/dto/UserDTO.java
  src/main/java/com/threeping/syncday/user/command/application/dto/UserEventDTO.java
  src/main/java/com/threeping/syncday/user/command/domain/aggregate/UserEntity.java
  src/main/java/com/threeping/syncday/user/config/UserEntityListener.java
  src/main/java/com/threeping/syncday/user/config/elasticsearch/UserSearchEventHandler.java
  src/main/java/com/threeping/syncday/user/infrastructure/elasticsearch/ElasticsearchInitializer.java
  src/main/java/com/threeping/syncday/user/infrastructure/elasticsearch/document/UserSearchDocument.java
  src/main/java/com/threeping/syncday/user/infrastructure/elasticsearch/repository/UserSearchRepository.java
  src/main/java/com/threeping/syncday/user/query/controller/UserQueryController.java
  src/main/java/com/threeping/syncday/user/query/dto/UserQueryDTO.java
  src/main/java/com/threeping/syncday/user/query/dto/UserSearchResponse.java
  src/main/java/com/threeping/syncday/user/query/repository/UserMapper.java
  src/main/java/com/threeping/syncday/user/query/service/UserQueryService.java
  src/main/java/com/threeping/syncday/user/query/service/UserQueryServiceImpl.java
  src/main/java/com/threeping/syncday/user/query/service/UserSearchService.java
  src/main/java/com/threeping/syncday/user/query/service/UserSearchServiceImpl.java
  src/main/resources/com/threeping/syncday/proj/query/repository/ProjMapper.xml
  src/main/resources/com/threeping/syncday/user/query/repository/UserMapper.xml
Labels: feat✨, BackEnd🔙

#79 refactor(schedule) : 일정 삭제 및 Swagger 수정
  src/main/java/com/threeping/syncday/schedule/command/Infrastructure/InfraScheduleService.java
  src/main/java/com/threeping/syncday/schedule/command/Infrastructure/InfraScheduleServiceImpl.java
  src/main/java/com/threeping/syncday/schedule/command/aggregate/dto/ScheduleDTO.java
  src/main/java/com/threeping/syncday/schedule/command/application/service/AppScheduleServiceImpl.java
  src/main/java/com/threeping/syncday/schedule/query/aggregate/ScheduleDTO.java
  src/main/java/com/threeping/syncday/schedule/query/controller/ScheduleController.java
  src/main/java/com/threeping/syncday/scheduleparticipant/command/application/service/AppScheduleParticipantService.java
  src/main/java/com/threeping/syncday/scheduleparticipant/command/application/service/AppScheduleParticipantServiceImpl.java
Labels: BackEnd🔙, refactor✂️

#80 [채팅] 웹소켓 연결 설정
  src/main/java/com/threeping/syncday/chat/JwtHandShakeInterceptor.java
  src/main/java/com/threeping/syncday/chat/application/ChatController.java
  src/main/java/com/threeping/syncday/chat/application/ChatService.java
  src/main/java/com/threeping/syncday/chat/config/ChatWebConfig.java
  src/main/java/com/threeping/syncday/chat/config/MongoConfig.java
  src/main/java/com/threeping/syncday/chat/config/WebSocketConfig.java
  src/main/java/com/threeping/syncday/chat/dto/ChatMessageDTO.java
  src/main/java/com/threeping/syncday/chat/dto/ChatRoomDTO.java
  src/main/java/com/threeping/syncday/chat/entity/ChatMessage.java
  src/main/java/com/threeping/syncday/chat/entity/ChatRoom.java
  src/main/java/com/threeping/syncday/chat/entity/ChatType.java
  src/main/java/com/threeping/syncday/chat/repository/ChatRoomRepository.java
  src/main/java/com/threeping/syncday/user/command/domain/repository/UserRepository.java
  src/main/java/com/threeping/syncday/user/security/JwtFilter.java
  src/main/java/com/threeping/syncday/user/security/WebSecurity.java
Labels: feat✨, BackEnd🔙

#81 Feature/schedule repeat 일정반복 swagger 설정 추가
  build.gradle
  src/main/java/com/threeping/syncday/config/SwaggerConfiguration.java
  src/main/java/com/threeping/syncday/schedulerepeat/command/aggregate/dto/CreateScheduleRepeatDTO.java
  src/main/java/com/threeping/syncday/schedulerepeat/command/aggregate/dto/ScheduleRepeatDTO.java
  src/main/java/com/threeping/syncday/schedulerepeat/command/application/controller/ScheduleRepeatCommandController.java
Labels: docs📖, BackEnd🔙

#86 [Cardboard] 생성 및 테스트코드
  src/main/java/com/threeping/syncday/cardboard/command/aggreate/dto/CardboardDTO.java
  src/main/java/com/threeping/syncday/cardboard/command/aggreate/entity/Cardboard.java
  src/main/java/com/threeping/syncday/cardboard/command/aggreate/entity/VcsType.java
  src/main/java/com/threeping/syncday/cardboard/command/aggreate/vo/AddCardboardVO.java
  src/main/java/com/threeping/syncday/cardboard/command/application/controller/AppCardboardController.java
  src/main/java/com/threeping/syncday/cardboard/command/application/service/AppCardboardService.java
  src/main/java/com/threeping/syncday/cardboard/command/application/service/AppCardboardServiceImpl.java
  src/main/java/com/threeping/syncday/cardboard/command/domain/repository/CardboardRepository.java
  src/main/java/com/threeping/syncday/cardboard/query/aggregate/Cardboard.java
  src/main/java/com/threeping/syncday/cardboard/query/aggregate/CardboardDTO.java
  src/main/java/com/threeping/syncday/cardboard/query/controller/CardboardController.java
  src/main/java/com/threeping/syncday/cardboard/query/repository/CardBoardMapper.java
  src/main/java/com/threeping/syncday/cardboard/query/repository/CardboardMapper.java
  src/main/java/com/threeping/syncday/cardboard/query/service/CardBoardService.java
  src/main/java/com/threeping/syncday/cardboard/query/service/CardBoardServiceImpl.java
  src/main/java/com/threeping/syncday/cardboard/query/service/CardboardService.java
  src/main/java/com/threeping/syncday/cardboard/query/service/CardboardServiceImpl.java
  src/main/java/com/threeping/syncday/proj/command/aggregate/entity/Proj.java
  src/main/java/com/threeping/syncday/workspace/query/aggregate/CardboardVO.java
  src/main/java/com/threeping/syncday/workspace/query/aggregate/WorkspaceInfoDTO.java
  src/main/java/com/threeping/syncday/workspace/query/respository/WorkspaceMapper.java
  src/main/resources/com/threeping/syncday/cardboard/query/repository/CardboardMapper.xml
  src/main/resources/com/threeping/syncday/workspace/query/respository/WorkspaceMapper.xml
  src/test/java/com/threeping/syncday/cardboard/command/application/service/AppCardboardServiceTests.java
  src/test/java/com/threeping/syncday/cardboard/query/service/CardboardServiceTests.java
Labels: feat✨, BackEnd🔙

#93 [Card] 생성 수정 삭제
  src/main/java/com/threeping/syncday/card/command/aggregate/dto/CardDTO.java
  src/main/java/com/threeping/syncday/card/command/aggregate/entity/Card.java
  src/main/java/com/threeping/syncday/card/command/aggregate/entity/VCSOBJECTTYPE.java
  src/main/java/com/threeping/syncday/card/command/aggregate/vo/RequestDeleteCardVO.java
  src/main/java/com/threeping/syncday/card/command/aggregate/vo/RequestUpdateCardVO.java
  src/main/java/com/threeping/syncday/card/command/application/AppCardService.java
  src/main/java/com/threeping/syncday/card/command/application/controller/AppCardController.java
  src/main/java/com/threeping/syncday/card/command/application/service/AppCardService.java
  src/main/java/com/threeping/syncday/card/command/application/service/AppCardServiceImpl.java
  src/main/java/com/threeping/syncday/card/command/domain/repository/CardRepository.java
  src/main/java/com/threeping/syncday/common/exception/ErrorCode.java
  src/test/java/com/threeping/syncday/card/command/application/service/AppCardServiceTests.java
Labels: feat✨, BackEnd🔙

#104 [CardBookmark] 조회 생성 수정 삭제 + 테스트코드
  src/main/java/com/threeping/syncday/cardbookmark/command/aggregate/dto/CardBookmarkDTO.java
  src/main/java/com/threeping/syncday/cardbookmark/command/aggregate/entity/CardBookmark.java
  src/main/java/com/threeping/syncday/cardbookmark/command/aggregate/vo/RequestCardBookmarkVO.java
  src/main/java/com/threeping/syncday/cardbookmark/command/application/controller/AppCardBookmarkController.java
  src/main/java/com/threeping/syncday/cardbookmark/command/application/service/AppCardBookmarkService.java
  src/main/java/com/threeping/syncday/cardbookmark/command/application/service/AppCardBookmarkServiceImpl.java
  src/main/java/com/threeping/syncday/cardbookmark/command/domain/repository/CardBookmarkRepository.java
  src/main/java/com/threeping/syncday/cardbookmark/query/aggregate/dto/CardBookmarkDTO.java
  src/main/java/com/threeping/syncday/cardbookmark/query/config/MybatisConfig.java
  src/main/java/com/threeping/syncday/cardbookmark/query/controller/CardBookmarkController.java
  src/main/java/com/threeping/syncday/cardbookmark/query/repository/CardBookmarkMapper.java
  src/main/java/com/threeping/syncday/cardbookmark/query/service/CardBookmarkService.java
  src/main/java/com/threeping/syncday/cardbookmark/query/service/CardBookmarkServiceImpl.java
  src/main/java/com/threeping/syncday/cardtag/query/aggregate/dto/CardTagDTO.java
  src/main/java/com/threeping/syncday/cardtag/query/config/MybatisConfig.java
  src/main/java/com/threeping/syncday/cardtag/query/controller/CardTagController.java
  src/main/java/com/threeping/syncday/cardtag/query/repository/CardTagMapper.java
  src/main/java/com/threeping/syncday/cardtag/query/service/CardTagService.java
  src/main/java/com/threeping/syncday/cardtag/query/service/CardTagServiceImpl.java
  src/main/java/com/threeping/syncday/common/exception/ErrorCode.java
  src/main/resources/com/threeping/syncday/cardbookmark/query/repository/CardBookmarkMapper.xml
  src/main/resources/com/threeping/syncday/cardtag/query/repository/CardTagMapper.xml
  src/test/java/com/threeping/syncday/cardbookmark/command/application/service/AppCardBookmarkServiceTests.java
  src/test/java/com/threeping/syncday/cardbookmark/query/service/CardBookmarkServiceTests.java
  src/test/java/com/threeping/syncday/cardtag/query/service/CardTagServiceTests.java
Labels: feat✨, BackEnd🔙

#112 feat: 북마크 프론트와 연동 구현
  src/main/java/com/threeping/syncday/projmember/command/application/controller/AppProjMemberController.java
  src/main/java/com/threeping/syncday/projmember/command/application/service/AppProjMemberService.java
  src/main/java/com/threeping/syncday/projmember/command/application/service/AppProjMemberServiceImpl.java
  src/main/java/com/threeping/syncday/projmember/command/domain/repository/ProjMemberRepository.java
Labels: feat✨, BackEnd🔙

#113 [vcs 정보추가] 프론트와 연동
  src/main/java/com/threeping/syncday/proj/command/aggregate/dto/ProjDTO.java
  src/main/java/com/threeping/syncday/proj/command/aggregate/vo/RequestUpdateVcsInfoVO.java
  src/main/java/com/threeping/syncday/proj/command/application/controller/AppProjController.java
  src/main/java/com/threeping/syncday/proj/command/application/service/AppProjService.java
  src/main/java/com/threeping/syncday/proj/command/application/service/AppProjServiceImpl.java
  src/main/java/com/threeping/syncday/proj/command/infrastructure/service/InfraProjService.java
  src/main/java/com/threeping/syncday/proj/command/infrastructure/service/InfraProjServiceImpl.java
  src/main/java/com/threeping/syncday/projmember/query/repository/ProjMemberMapper.java
  src/main/java/com/threeping/syncday/projmember/query/service/ProjMemberService.java
  src/main/java/com/threeping/syncday/projmember/query/service/ProjMemberServiceImpl.java
  src/main/resources/com/threeping/syncday/projmember/query/repository/ProjMemberMapper.xml
  src/test/java/com/threeping/syncday/proj/command/application/service/AppProjServiceTests.java
  src/test/java/com/threeping/syncday/proj/query/service/ProjServiceTests.java
Labels: feat✨, BackEnd🔙

#114 [일정알림] 일정 시작 전 알림 기능 추가
  src/main/java/com/threeping/syncday/notification/controller/NotificationSseController.java
  src/main/java/com/threeping/syncday/notification/redis/RedisNotificationSubscriber.java
  src/main/java/com/threeping/syncday/notification/service/NotificationScheduler.java
  src/main/java/com/threeping/syncday/notification/service/NotificationService.java
  src/main/java/com/threeping/syncday/notification/service/NotificationServiceImpl.java
  src/main/java/com/threeping/syncday/notification/service/TestUserSchedule.java
Labels: BackEnd🔙, refactor✂️

#116 [팀게시판] 팀 게시판 CRUD 기능 추가
  src/main/java/com/threeping/syncday/teamboard/command/aggregate/dto/TeamBoardDTO.java
  src/main/java/com/threeping/syncday/teamboard/command/aggregate/entity/TeamBoard.java
  src/main/java/com/threeping/syncday/teamboard/command/application/controller/TeamBoardCommandController.java
  src/main/java/com/threeping/syncday/teamboard/command/domain/repository/TeamBoardRepository.java
  src/main/java/com/threeping/syncday/teamboard/command/service/TeamBoardCommandService.java
  src/main/java/com/threeping/syncday/teamboard/command/service/TeamBoardCommandServiceImpl.java
  src/main/java/com/threeping/syncday/teamboard/query/config/MybatisConfig.java
  src/main/java/com/threeping/syncday/teamboard/query/controller/TeamBoardQueryController.java
  src/main/java/com/threeping/syncday/teamboard/query/repository/TeamBoardMapper.java
  src/main/java/com/threeping/syncday/teamboard/query/service/TeamBoardQueryService.java
  src/main/java/com/threeping/syncday/teamboard/query/service/TeamBoardQueryServiceImpl.java
  src/main/resources/com/threeping/syncday/teamboard/query/repository/TeamBoardMapper.xml
Labels: feat✨, BackEnd🔙

#115 워크스페이스 검색 기능 구현
  src/main/java/com/threeping/syncday/proj/infrastructure/elasticsearch/repository/ProjSearchRepository.java
  src/main/java/com/threeping/syncday/proj/query/service/ProjectSearchServiceImpl.java
  src/main/java/com/threeping/syncday/schedule/command/aggregate/dto/ScheduleDTO.java
  src/main/java/com/threeping/syncday/user/infrastructure/elasticsearch/document/UserSearchDocument.java
  src/main/java/com/threeping/syncday/user/infrastructure/elasticsearch/repository/UserSearchRepository.java
  src/main/java/com/threeping/syncday/user/query/service/UserSearchServiceImpl.java
  src/main/java/com/threeping/syncday/workspace/command/aggregate/dto/WorkspaceEventDTO.java
  src/main/java/com/threeping/syncday/workspace/command/aggregate/entity/Workspace.java
  src/main/java/com/threeping/syncday/workspace/command/aggregate/vo/WorkspaceVO.java
  src/main/java/com/threeping/syncday/workspace/infrastructure/elasticsearch/ElasticsearchInitializer.java
  src/main/java/com/threeping/syncday/workspace/infrastructure/elasticsearch/document/WorkSpaceDocument.java
  src/main/java/com/threeping/syncday/workspace/infrastructure/elasticsearch/repository/WorkSpaceSearchRepository.java
  src/main/java/com/threeping/syncday/workspace/query/aggregate/Workspace.java
  src/main/java/com/threeping/syncday/workspace/query/aggregate/WorkspaceDTO.java
  src/main/java/com/threeping/syncday/workspace/query/config/WorkspaceEntityListener.java
  src/main/java/com/threeping/syncday/workspace/query/config/elasticsearch/WorkspaceSearchEventHandler.java
  src/main/java/com/threeping/syncday/workspace/query/controller/WorkspaceController.java
  src/main/java/com/threeping/syncday/workspace/query/dto/WorkspaceQueryDTO.java
  src/main/java/com/threeping/syncday/workspace/query/dto/WorkspaceSearchResponse.java
  src/main/java/com/threeping/syncday/workspace/query/respository/WorkspaceMapper.java
  src/main/java/com/threeping/syncday/workspace/query/service/WorkspaceSearchService.java
  src/main/java/com/threeping/syncday/workspace/query/service/WorkspaceSearchServiceImpl.java
  src/main/resources/com/threeping/syncday/workspace/query/respository/WorkspaceMapper.xml
Labels: feat✨, BackEnd🔙, fix🛠️
