Repository three-ping/SyncDay_Back, pull requests merged in 2024-12, with the labels that each got.

#117 [팀게시글] 팀 게시글 CRUD 기능 추가
  build.gradle
  src/main/java/com/threeping/syncday/teampost/command/aggregate/dto/TeamPostDTO.java
  src/main/java/com/threeping/syncday/teampost/command/aggregate/entity/TeamPost.java
  src/main/java/com/threeping/syncday/teampost/command/application/controller/TeamPostCommandController.java
  src/main/java/com/threeping/syncday/teampost/command/application/service/TeamPostCommandService.java
  src/main/java/com/threeping/syncday/teampost/command/application/service/TeamPostCommandServiceImpl.java
  src/main/java/com/threeping/syncday/teampost/command/domain/repository/TeamPostRepository.java
  src/main/java/com/threeping/syncday/teampost/query/aggregate/dto/TeamPostDTO.java
  src/main/java/com/threeping/syncday/teampost/query/config/MybatisConfig.java
  src/main/java/com/threeping/syncday/teampost/query/controller/TeamPostQueryController.java
  src/main/java/com/threeping/syncday/teampost/query/repository/TeamPostMapper.java
  src/main/java/com/threeping/syncday/teampost/query/service/TeamPostQueryService.java
  src/main/java/com/threeping/syncday/teampost/query/service/TeamPostQueryServiceImpl.java
  src/main/resources/com/threeping/syncday/teampost/query/repository/TeamPostMapper.xml
Labels: feat✨, BackEnd🔙

#118 [채팅] 메세지 전송 성공
  build.gradle
  src/main/java/com/threeping/syncday/chat/application/ChatController.java
  src/main/java/com/threeping/syncday/chat/application/ChatService.java
  src/main/java/com/threeping/syncday/chat/config/MongoConfig.java
  src/main/java/com/threeping/syncday/chat/config/WebSocketConfig.java
  src/main/java/com/threeping/syncday/chat/controller/ChatController.java
  src/main/java/com/threeping/syncday/chat/dto/ChatMessageDTO.java
  src/main/java/com/threeping/syncday/chat/dto/ChatRoomDTO.java
  src/main/java/com/threeping/syncday/chat/entity/ChatMessage.java
  src/main/java/com/threeping/syncday/chat/entity/ChatRoom.java
  src/main/java/com/threeping/syncday/chat/entity/ChatType.java
  src/main/java/com/threeping/syncday/chat/repository/ChatMessageRepository.java
  src/main/java/com/threeping/syncday/chat/repository/ChatRoomRepository.java
  src/main/java/com/threeping/syncday/chat/service/ChatService.java
  src/main/java/com/threeping/syncday/user/command/application/service/UserCommandService.java
  src/main/java/com/threeping/syncday/user/command/application/service/UserCommandServiceImpl.java
  src/main/java/com/threeping/syncday/user/command/domain/repository/UserRepository.java
  src/main/java/com/threeping/syncday/user/security/WebSecurity.java
Labels: feat✨, BackEnd🔙

#119 [팀댓글] 팀 댓글 CRUD 기능 추가
  src/main/java/com/threeping/syncday/teamboard/command/application/controller/TeamBoardCommandController.java
  src/main/java/com/threeping/syncday/teamboard/command/application/service/TeamBoardCommandService.java
  src/main/java/com/threeping/syncday/teamboard/command/application/service/TeamBoardCommandServiceImpl.java
  src/main/java/com/threeping/syncday/teamcomment/command/aggregate/dto/TeamCommentDTO.java
  src/main/java/com/threeping/syncday/teamcomment/command/aggregate/entity/TeamComment.java
  src/main/java/com/threeping/syncday/teamcomment/command/application/controller/TeamCommentCommandController.java
  src/main/java/com/threeping/syncday/teamcomment/command/application/service/TeamCommentCommandService.java
  src/main/java/com/threeping/syncday/teamcomment/command/application/service/TeamCommentCommandServiceImpl.java
  src/main/java/com/threeping/syncday/teamcomment/command/domain/repository/TeamCommentRepository.java
  src/main/java/com/threeping/syncday/teamcomment/query/aggregate/dto/TeamCommentDTO.java
  src/main/java/com/threeping/syncday/teamcomment/query/config/MybatisConfig.java
  src/main/java/com/threeping/syncday/teamcomment/query/controller/TeamCommentQueryController.java
  src/main/java/com/threeping/syncday/teamcomment/query/repository/TeamCommentMapper.java
  src/main/java/com/threeping/syncday/teamcomment/query/service/TeamCommentQueryService.java
  src/main/java/com/threeping/syncday/teamcomment/query/service/TeamCommentQueryServiceImpl.java
  src/main/resources/com/threeping/syncday/teamcomment/query/repository/TeamCommentMapper.xml
Labels: feat✨, BackEnd🔙

#120 [채팅] 몽고db 데이터 수정
  src/main/java/com/threeping/syncday/chat/config/MongoConfig.java
Labels: bug, BackEnd🔙, fix🛠️

#121 refactor: 회의실 예약 수정
  src/main/java/com/threeping/syncday/meetingroomreservation/query/aggregate/MeetingroomReservation.java
  src/main/java/com/threeping/syncday/meetingroomreservation/query/aggregate/MeetingroomReservationDTO.java
  src/main/java/com/threeping/syncday/meetingroomreservation/query/controller/MeetingroomReservationController.java
  src/main/java/com/threeping/syncday/meetingroomreservation/query/repository/MeetingroomReservationMapper.java
  src/main/java/com/threeping/syncday/meetingroomreservation/query/service/MeetingroomReservationService.java
  src/main/java/com/threeping/syncday/meetingroomreservation/query/service/MeetingroomReservationServiceImpl.java
  src/main/resources/com/threeping/syncday/meetingroomreservation/query/repository/MeetingroomReservationMapper.xml
Labels: BackEnd🔙, refactor✂️

#123 [회의실] 회의실 예약코드 수정
  src/main/java/com/threeping/syncday/meetingroomreservation/query/aggregate/MeetingroomReservation.java
  src/main/java/com/threeping/syncday/meetingroomreservation/query/aggregate/MeetingroomReservationDTO.java
  src/main/resources/com/threeping/syncday/meetingroomreservation/query/repository/MeetingroomReservationMapper.xml
Labels: BackEnd🔙, refactor✂️

#124 [일정참석] 일정 참석여부 조회를 위한 메소드 추가 / [알림] SSE 연결 타임아웃 오류 수정
  src/main/java/com/threeping/syncday/notification/service/NotificationServiceImpl.java
  src/main/java/com/threeping/syncday/scheduleparticipant/query/aggregate/ScheduleAttendanceDTO.java
  src/main/java/com/threeping/syncday/scheduleparticipant/query/controller/ScheduleParticipantController.java
  src/main/java/com/threeping/syncday/scheduleparticipant/query/repository/ScheduleParticipantMapper.java
  src/main/java/com/threeping/syncday/scheduleparticipant/query/service/ScheduleParticipantService.java
  src/main/java/com/threeping/syncday/scheduleparticipant/query/service/ScheduleParticipantServiceImpl.java
  src/main/resources/com/threeping/syncday/scheduleparticipant/query/repository/ScheduleParticipantMapper.xml
Labels: BackEnd🔙

#126 [회의실] 회의실 예약 쿼리 수정
  src/main/java/com/threeping/syncday/meetingroomreservation/query/aggregate/MeetingroomReservation.java
  src/main/java/com/threeping/syncday/meetingroomreservation/query/aggregate/MeetingroomReservationDTO.java
  src/main/java/com/threeping/syncday/proj/command/application/controller/AppProjController.java
  src/main/resources/com/threeping/syncday/meetingroomreservation/query/repository/MeetingroomReservationMapper.xml
Labels: BackEnd🔙, refactor✂️

#129 [팀] 팀 게시판 관련 DTO와 쿼리 수정
  src/main/java/com/threeping/syncday/team/query/aggregate/MyTeamDTO.java
  src/main/java/com/threeping/syncday/team/query/controller/TeamController.java
  src/main/java/com/threeping/syncday/team/query/repository/TeamMapper.java
  src/main/java/com/threeping/syncday/team/query/service/TeamService.java
  src/main/java/com/threeping/syncday/team/query/service/TeamServiceImpl.java
  src/main/java/com/threeping/syncday/teamcomment/query/aggregate/dto/TeamCommentDTO.java
  src/main/java/com/threeping/syncday/teampost/query/aggregate/dto/TeamPostDTO.java
  src/main/java/com/threeping/syncday/teampost/query/controller/TeamPostQueryController.java
  src/main/java/com/threeping/syncday/teampost/query/repository/TeamPostMapper.java
  src/main/java/com/threeping/syncday/teampost/query/service/TeamPostQueryService.java
  src/main/java/com/threeping/syncday/teampost/query/service/TeamPostQueryServiceImpl.java
  src/main/resources/com/threeping/syncday/team/query/repository/TeamMapper.xml
  src/main/resources/com/threeping/syncday/teamcomment/query/repository/TeamCommentMapper.xml
  src/main/resources/com/threeping/syncday/teampost/query/repository/TeamPostMapper.xml
Labels: BackEnd🔙, refactor✂️

#131 [일정] 오늘의 본인 일정 조회 기능 추가
  src/main/java/com/threeping/syncday/schedule/query/aggregate/MyTodayScheduleDTO.java
  src/main/java/com/threeping/syncday/schedule/query/controller/ScheduleController.java
  src/main/java/com/threeping/syncday/schedule/query/repository/ScheduleMapper.java
  src/main/java/com/threeping/syncday/schedule/query/service/ScheduleService.java
  src/main/java/com/threeping/syncday/schedule/query/service/ScheduleServiceImpl.java
  src/main/resources/com/threeping/syncday/schedule/query/repository/ScheduleMapper.xml
Labels: feat✨, BackEnd🔙

#133 [프로젝트] 백엔드 코드 수정
  src/main/java/com/threeping/syncday/projmember/query/aggregate/ProjMember.java
  src/main/java/com/threeping/syncday/projmember/query/aggregate/ProjMemberDTO.java
  src/main/resources/com/threeping/syncday/projmember/query/repository/ProjMemberMapper.xml
Labels: BackEnd🔙, refactor✂️

#134 [일정] 일정 생성 시 메일 발송 기능 추가
  src/main/java/com/threeping/syncday/SyncdayApplication.java
  src/main/java/com/threeping/syncday/notification/service/NotificationScheduler.java
  src/main/java/com/threeping/syncday/schedule/command/Infrastructure/InfraScheduleService.java
  src/main/java/com/threeping/syncday/schedule/command/Infrastructure/InfraScheduleServiceImpl.java
  src/main/java/com/threeping/syncday/schedule/command/application/controller/AppScheduleController.java
  src/main/java/com/threeping/syncday/schedule/command/application/service/AppScheduleService.java
  src/main/java/com/threeping/syncday/schedule/command/application/service/AppScheduleServiceImpl.java
  src/main/java/com/threeping/syncday/scheduleparticipant/command/application/service/AppScheduleParticipantServiceImpl.java
  src/main/resources/com/threeping/syncday/schedule/query/repository/ScheduleMapper.xml
  src/main/resources/templates/SCHEDULE.html
Labels: feat✨, BackEnd🔙

#136 [카드보드] CardboardVO 수정
  src/main/java/com/threeping/syncday/cardboard/command/aggreate/vo/AppCardboardVO.java
Labels: BackEnd🔙, refactor✂️

#138 refactor(schedule) : 일정 조회 수정
  src/main/java/com/threeping/syncday/schedule/command/application/service/AppScheduleServiceImpl.java
  src/main/java/com/threeping/syncday/schedule/query/aggregate/ScheduleDTO.java
  src/main/java/com/threeping/syncday/schedule/query/aggregate/ScheduleDetailDTO.java
  src/main/java/com/threeping/syncday/schedule/query/aggregate/UserInfoDTO.java
  src/main/resources/com/threeping/syncday/schedule/query/repository/ScheduleMapper.xml
Labels: BackEnd🔙, refactor✂️

#141 [채팅] 채팅방 생성 함수 수정 및 몽고 더미데이터 추가
  src/main/java/com/threeping/syncday/chat/application/ChatController.java
  src/main/java/com/threeping/syncday/chat/config/MongoConfig.java
  src/main/java/com/threeping/syncday/chat/dto/ChatMessageDTO.java
Labels: BackEnd🔙, fix🛠️

#143 [채팅] 특정 채팅방 조회
  src/main/java/com/threeping/syncday/chat/application/ChatController.java
  src/main/java/com/threeping/syncday/chat/application/ChatService.java
  src/main/java/com/threeping/syncday/chat/config/MongoConfig.java
  src/main/java/com/threeping/syncday/chat/dto/ChatRoomDTO.java
  src/main/java/com/threeping/syncday/chat/repository/ChatMessageRepository.java
Labels: feat✨, BackEnd🔙, fix🛠️

#146 [카드태그] 카드 태그부분 백엔드 코드 추가
  src/main/java/com/threeping/syncday/cardtag/query/controller/CardTagController.java
  src/main/java/com/threeping/syncday/cardtag/query/repository/CardTagMapper.java
  src/main/java/com/threeping/syncday/cardtag/query/service/CardTagService.java
  src/main/java/com/threeping/syncday/cardtag/query/service/CardTagServiceImpl.java
  src/main/java/com/threeping/syncday/meetingroom/query/aggregate/Meetingroom.java
  src/main/java/com/threeping/syncday/meetingroom/query/aggregate/MeetingroomDTO.java
  src/main/java/com/threeping/syncday/meetingroom/query/controller/MeetingroomController.java
  src/main/java/com/threeping/syncday/meetingroomreservation/command/aggregate/dto/MeetingroomReservationDTO.java
  src/main/java/com/threeping/syncday/meetingroomreservation/command/application/service/AppMeetingroomReservationServiceImpl.java
  src/main/java/com/threeping/syncday/meetingroomreservation/query/aggregate/MeetingroomReservation.java
  src/main/java/com/threeping/syncday/meetingroomreservation/query/aggregate/MeetingroomReservationDTO.java
  src/main/java/com/threeping/syncday/projmember/command/aggregate/entity/ProjMember.java
  src/main/java/com/threeping/syncday/projmember/command/application/service/AppProjMemberServiceImpl.java
  src/main/resources/com/threeping/syncday/cardtag/query/repository/CardTagMapper.xml
  src/main/resources/com/threeping/syncday/meetingroomreservation/query/repository/MeetingroomReservationMapper.xml
  src/test/java/com/threeping/syncday/meetingroom/query/controller/MeetingroomControllerTests.java
  src/test/java/com/threeping/syncday/meetingroomreservation/query/service/MeetingroomReservationServiceTests.java
Labels: feat✨, BackEnd🔙

#151 refactor: serviceImpl 수정
  src/main/java/com/threeping/syncday/config/AwsConfig.java
  src/main/java/com/threeping/syncday/projmember/command/application/service/AppProjMemberServiceImpl.java
Labels: BackEnd🔙, refactor✂️

#153 refactor(schedule) : 일정 수정
  src/main/java/com/threeping/syncday/schedule/command/aggregate/dto/ScheduleDTO.java
  src/main/java/com/threeping/syncday/schedule/command/application/service/AppScheduleServiceImpl.java
  src/main/java/com/threeping/syncday/schedule/query/aggregate/AttendeeDTO.java
  src/main/java/com/threeping/syncday/schedule/query/aggregate/ScheduleDTO.java
  src/main/java/com/threeping/syncday/schedulerepeat/command/infrastructure/service/InfraScheduleRepeatServiceImpl.java
  src/main/resources/com/threeping/syncday/schedule/query/repository/ScheduleMapper.xml
Labels: BackEnd🔙, refactor✂️

#155 refactor: 카드 수정
  src/main/java/com/threeping/syncday/card/command/aggregate/dto/CardDTO.java
  src/main/java/com/threeping/syncday/card/command/application/service/AppCardServiceImpl.java
Labels: BackEnd🔙, refactor✂️

#157 refactor(schedule) : 타인 일정 조회 수정
  src/main/resources/com/threeping/syncday/schedule/query/repository/ScheduleMapper.xml
Labels: BackEnd🔙, refactor✂️

#158 [채팅] date 타입 변경
  build.gradle
  src/main/java/com/threeping/syncday/chat/application/ChatController.java
  src/main/java/com/threeping/syncday/chat/application/ChatService.java
  src/main/java/com/threeping/syncday/chat/config/MongoConfig.java
  src/main/java/com/threeping/syncday/chat/dto/ChatMessageDTO.java
  src/main/java/com/threeping/syncday/chat/entity/ChatMessage.java
  src/main/java/com/threeping/syncday/chat/entity/ChatRoom.java
  src/main/java/com/threeping/syncday/chat/repository/ChatRoomRepository.java
Labels: BackEnd🔙, fix🛠️

#159 refactor(schedule) : 일정 수정
  src/main/java/com/threeping/syncday/schedule/query/aggregate/ScheduleDetailDTO.java
  src/main/resources/com/threeping/syncday/schedule/query/repository/ScheduleMapper.xml
Labels: BackEnd🔙, refactor✂️
